"""update game model

Revision ID: 5b6c65fcecb0
Revises: 6b118fa1f506
Create Date: 2023-01-27 11:20:25.743925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b6c65fcecb0'
down_revision = '6b118fa1f506'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
