"""add __repr__ method to game model

Revision ID: 6819ee973963
Revises: 5b6c65fcecb0
Create Date: 2023-01-27 11:24:04.651977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6819ee973963'
down_revision = '5b6c65fcecb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
