"""fix review table

Revision ID: f6e35664a92f
Revises: 6819ee973963
Create Date: 2023-01-27 11:27:01.031357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e35664a92f'
down_revision = '6819ee973963'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('review_score', sa.Integer(), nullable=True))
    op.drop_column('reviews', 'score')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('score', sa.INTEGER(), nullable=True))
    op.drop_column('reviews', 'review_score')
    # ### end Alembic commands ###
