"""fix review table again

Revision ID: fa40ee235867
Revises: f6e35664a92f
Create Date: 2023-01-27 11:27:26.124263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa40ee235867'
down_revision = 'f6e35664a92f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
